### ISSUE TITLE
LED控制

### ISSUE THREAD

**Issue by LoveMiku233** [LoveMiku233/lanqiao51#2]
学习任务

**Comment by piaochangli** [comment]
#include <STC15F2K60S2.H>

void main(void)
{
	while(1)
	{
		P2 |=(1<<7);
		P2 &= ~((1<<6)|(1<<5)); 
		//使能端赋值 P27 P26 P25
		
		P0=0xAA; // 1010 1010
	}
}

**Comment by piaochangli** [comment]
#include <STC15F2K60S2.H>

void main(void)
{
	while(1)
	{
		P2 |=(1<<7);
		P2 &= ~((1<<6)|(1<<5)); 
		//使能端赋值 P27 P26 P25
		
		P0=0xAA; // 1010 1010
	}
}

**Comment by piaochangli** [comment]
```
#include <STC15F2K60S2.H>

void main(void)
{
while(1)
{
P2 |=(1<<7);
P2 &= ~((1<<6)|(1<<5));

	P0=0xAA; // 1010 1010
}
}
```

**Comment by LoveMiku233** [comment]
@YaYazzz
